export enum TextStyle {
	HEADING_1 = 'HEADING_1',
	HEADING_2 = 'HEADING_2',
	HEADING_3 = 'HEADING_3',
	HEADING_4 = 'HEADING_4',
	HEADING_5 = 'HEADING_5',
	HEADING_6 = 'HEADING_6',
	BODY_1 = 'BODY_1',
	BODY_2 = 'BODY_2',
	PARAGRAPH = 'PARAGRAPH',
	CAPTION = 'CAPTION',
}
